### ISSUE TITLE
High CPU usage for vertical tabs in firefox 37.0.2

### ISSUE THREAD

**Issue by sblatnick** [tabkit/tabkit2#85] opened 2015-05-01 15:54 UTC
My firefox just updated to 37.0.2 for 64-bit linux, and now firefox uses 100% of a single CPU in my system monitor.

I put tabs on the right side, but I see this behavior independent of side.  If I set the tabs to top or bottom instead of vertically on the side, the CPU usage returns to normal.

**Comment by PikachuEXE** [comment] 2015-05-02 00:44
I cannot reproduce such issue with Firefox Portable 37.0.2 on Windows 7
This could be related to other extensions. Try disabling other extensions to see if the problem still persist.
Or you can try to reproduce with Firefox Portable on Windows 7 (using VM or other means).
Then send the whole folder to me (after archiving)

**Comment by denis-martin** [comment] 2015-05-04 11:34
I'm experiencing a similar issue: There is a constant CPU-load (around 8% on my system). It seems to be related to Tab Kit 2 v0.12.2 + Classic Theme Restorer v1.3.1.1. If either of the addons is disabled, the CPU-load goes down (reproduced with Firefox portable).

**Comment by sblatnick** [comment] 2015-05-05 05:46
I also use the classic theme restorer, although I disabled it to make sure it wasn't the cause and still saw the performance issue.  I have not tried  disabling all of my other plugins yet, sorry.  It could be interacting with another plugin, so I'll have to try.  With just this plugin disabled, the CPU returns to normal.
On May 4, 2015 5:34 AM, denis <notifications@github.com> wrote:I'm experiencing a similar issue: There is a constant CPU-load (around 8% on my system). It seems to be related to Tab Kit 2 v0.12.2 + Classic Theme Restorer v1.3.1.1. If either of the addons is disabled, the CPU-load goes down (reproduced with Firefox portable).

**Comment by PikachuEXE** [comment] 2015-05-05 05:47
Let me check it this weekend ~_~

**Comment by sblatnick** [comment] 2015-05-05 15:46
I just disabled all of my plugins except for Tab Kit 2, and the CPU usage was fine.  Then I enabled the Classic Theme Restorer, and that's when the CPU jumped up.  So I can confirm, it's this combination of plugins.  Without Classic Theme Restorer, the tabs look funny when vertical, as they have rounded corners.  Maybe you could add some tab theming fixes/options to Tab Kit 2?  Thanks for an awesome plugin though :-D  I'm surprised vertical tabs aren't more common, and it seems like with Firefox's new release schedule, they may be breaking plugins much more often.

**Comment by Aris-t2** [comment] 2015-05-05 21:51
I found what was causing this, but I think its an error in Tab Kit 2 triggered by CTRs code.

For no explainable reason this code causes high(er) CPU load even without CTR installed (when used in Stylish for example):

.tab-background {
-moz-margin-end: 0 !important;
-moz-margin-start: 0 !important;
}

Next CTR beta will fix this issue by excluding the above code from vertical tabs.

By the way Firefox developer theme uses that code by default.

Install 1.3.2beta2 and report back:
https://addons.mozilla.org/addon/classicthemerestorer/versions

**Comment by a-bronx** [comment] 2015-05-05 23:01
Also I noticed that if you drag one of the tabs to the bottom of the stack, then CPU % drops, but only when the last tab is active. Switching to another tab brings the CPU % back to high. May be helpful, may be not, just an observation.

The CTR beta fixed the issue on my FF 37.0.2, thank you!

**Comment by denis-martin** [comment] 2015-05-06 08:07
Yep, with CTR 1.3.2beta2 the load is back to normal, thanks!

**Comment by PikachuEXE** [comment] 2015-05-06 08:09
Let's wait for CTR 1.3.2 to be released and let a few people confirmed it's fixed before closing this issue.
I guess no need to put this in README right? :wink:

**Comment by sblatnick** [comment] 2015-05-07 15:37
I can confirm: 1.3.2beta2 fixed the problem for me too.

**Comment by t0mk** [comment] 2015-05-08 08:39
the CTR 1.3.2beta2 fixed the high load and also this weird epileptic blinking of the tab sidebar. Thanks for the tip!

**Comment by PikachuEXE** [comment] 2015-05-08 22:56
Can't reproduce on my computer :P 
I guess maybe wait for 38.x to see if that happens again

**Comment by Aris-t2** [comment] 2015-05-09 09:38
I don't think its Firefox related, I could reproduce it with Fx37-40 before the fix. Maybe you have a very powerful CPU. In my tests on a i5-2500k CPU usage jumped from 0-3% to 8-10% usage, so I wasn't sure first.

Install the non-fixed version of CTR, set tab appearance to "Curved tabs (Fx default)", open task manager and look at CPU usage of Firefox. Then enable "Squared tabs" and compare the values in Task manager.

**Comment by clopez** [comment] 2015-05-15 18:19
I confirm the bug

Maybe the issue only happens on Linux? Running Debian 64 bits here and Firefox 38.

**Comment by clopez** [comment] 2015-05-15 18:24
I also confirm that upgrading CTR to 1.3.2beta2 fixes the issue:

https://addons.mozilla.org/firefox/downloads/file/314446/classic_theme_restorer_customize_ui-1.3.2beta2-fx.xpi

**Comment by gituser** [comment] 2015-05-15 18:33
there is still quite high CPU usage if you just move mouse up and down
through tabkit tablist on the left sidebar or right sidebar ..

2015-05-15 21:24 GMT+03:00 Carlos Alberto Lopez Perez <
notifications@github.com>:

**Comment by PikachuEXE** [comment] 2015-08-30 02:10
Still an issue now? @gituser 
Please provide OS, Firefox version & extension version if the issue still exists.
Otherwise I will close this next week.

**Comment by gpdd** [comment] 2015-09-05 03:40
I have same issues even without tabkit extension (linux mint)

**Comment by Aris-t2** [comment] 2015-09-05 09:58
@gpdd 
Are you having this issue with latest CTR on latest Firefox release build?

**Comment by gpdd** [comment] 2015-09-05 18:46
@Aris-t2
No, i don't have CTR.

**Comment by denis-martin** [comment] 2016-02-08 19:14
Somehow, this bug is back again. Even the old beta-build of CTR linked here causes the same high CPU load. The same can be observed with the very simple addon "Squared Australis Tabs". Could you look into it again? It only happens with vertical tabs in tabkit. With horizontal tabs, everything is fine.

**Comment by PikachuEXE** [comment] 2016-02-08 23:18
@denis-martin 
You can:
- Try different versions of TK2
- Try different versions of Firefox
- Contact CTR people again

This is likely a bug in Firefox when some specific style rules are applied.

**Comment by Aris-t2** [comment] 2016-02-09 00:16
I get the same CPU usage values with and without CTR installed, nothing changed:
TK2 v0.12.4 + Fx44 (new Fx profile) + latest CTR beta

@PikachuEXE
You may already be aware of it, but TK2 does not work on Fx45+ (tabs can not be closed).
TK2 v0.12.4 + Fx45-47 (new Fx profile)

**Comment by PikachuEXE** [comment] 2016-02-09 00:42
Try FF ESR 38
New versions of FF might have new bugs

**Comment by Aris-t2** [comment] 2016-02-09 11:30
I know TK2 works with Fx38ESR, just wanted to remind you about the next ESR release in about a month: Fx45ESR. ;-)

**Comment by PikachuEXE** [comment] 2016-02-09 13:55
Got to kill FF dev again z_z

**Comment by PikachuEXE** [comment] 2016-05-01 12:51
Closing since the issue seems to be fixed already (by another extension)

**Closed by PikachuEXE** 2016-05-01 12:51 UTC
Labels: kind/firefox related
