### ISSUE TITLE
Group by opener stopped working if searchbar is removed

### ISSUE THREAD

**Issue by tadu** [tabkit/tabkit2#107] opened 2016-04-03 12:00 UTC
Using either 0.12.6 or 0.12.7, grouping by opened stopped working. Any link middle-clicked will just be opened and shown as a new, unrelated, ungrouped tab. Reverting to default settings (which have the same setting: group tabs by opened) did not help, either.

**Comment by PikachuEXE** [comment] 2016-04-03 23:33
What OS/FF are you using?

**Comment by Blessun** [comment] 2016-04-08 06:37
0.12.7 Prompt where to download?

**Comment by PikachuEXE** [comment] 2016-04-08 06:40
I have to delete it since they disable it somehow
But I cannot upload with the same version again

Maybe I will just "release" another version with no changes included

**Comment by PikachuEXE** [comment] 2016-04-17 09:34
https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/?page=1#version-0.12.8
Just released another version, can you try? Thanks

**Comment by tadu** [comment] 2016-04-23 21:01
I'm using FF 45, ... now 45.0.2, on (K)Ubuntu 14.04.
However, my "normal" FF for browsing is sandboxed, and has a profile aeons old. If I try it on the un-sandboxed, normal installation with almost empty profile it works. I already tried installing additional extension that I have also installed on my "normal" FF, and started comparing about:config settings, but to no avail so far. I'm still reasonable sure it must be something profile related that triggers it.

And no, 0.12.8 doesn't make any difference - it still breaks in my "normal" FF.

**Comment by PikachuEXE** [comment] 2016-04-23 23:15
Hmm would be easier to debug if you can send me your profile (after cleaning out personal stuff)
Hard to reproduce this bug :(

**Comment by tadu** [comment] 2016-04-25 20:09
One more thing I noticed: if I click on a link that opens in new tab/window, it is opened as related, if I middle click to open a link in a new tab/window, it is not.
However, if I set extensions.tabkit.newTabsAreRelated to true, then middle clicked links open a related tab. (Of course, new tabs, or e.g. Extras->AddOns to open about:config, do as well.)
Considering that the new tab is opened below the old one and then, if there are more tabs in the tab group, moves above it, it seems something is causing it to be re-considered as a new tab.

**Comment by PikachuEXE** [comment] 2016-05-01 11:53
I can open links with middle mouse button click with `extensions.tabkit.newTabsAreRelated` set to `false`
I am using `45.1.0`
Let me throw another release soon to see if the problem is already fixed

**Comment by tadu** [comment] 2016-05-04 22:46
Okay, I can boil it down to the setting of the browser.uiCustomization.state preference.

Works:
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"developer-button\",\"sync-button\"],\"status4evar-status-bar\":[\"status4evar-status-widget\",\"status4evar-progress-widget\",\"status4evar-download-button\",\"status4evar-legacy-widget\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\",\"ctraddon_tabs-closebutton\"],\"nav-bar\":[\"ctraddon_appbutton\",\"ctraddon_back-forward-button\",\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"sessionmanager-toolbar\",\"sessionmanager-undo\",\"downloads-button\",\"home-button\",\"social-share-button\",\"abp-toolbarbutton\",\"loop-button-throttled\",\"loop-button\",\"add-ons-button\",\"fnvfox_toolbarButton\",\"action-button--b9db16a4-6edc-47ec-a1f4-b86292ed211d-vdh-tbbutton\",\"vdpro-toolbarbutton\",\"ublock0-button\",\"noscript-tbb\",\"action-button--firefoxghosterycom-ghostery-button\",\"ctraddon_puib_separator\",\"ctraddon_panelui-button\",\"toggle-button--compatibilityaddonsmozillaorg-acr-dialog\",\"secureLoginButton\",\"greasemonkey-tbb\"],\"PersonalToolbar\":[\"personal-bookmarks\",\"ctraddon_bookmarks-menu-toolbar-button\"],\"ctraddon_addon-bar\":[\"ctraddon_addonbar-close\",\"customizableui-special-spring1\",\"ctraddon_statusbar\"],\"web-developer-toolbar\":[\"web-developer-disable-toolbar\",\"web-developer-cookies-toolbar\",\"web-developer-css-toolbar\",\"web-developer-forms-toolbar\",\"web-developer-images-toolbar\",\"web-developer-information-toolbar\",\"web-developer-miscellaneous-toolbar\",\"web-developer-outline-toolbar\",\"web-developer-resize-toolbar\",\"web-developer-tools-toolbar\",\"web-developer-view-source-toolbar\",\"web-developer-options-toolbar\",\"customizableui-special-spring8\",\"web-developer-render-mode-statusbar\",\"web-developer-css-statusbar\",\"web-developer-javascript-statusbar\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"ctraddon_extra-bar\":[\"customizableui-special-spring2\"]},\"seen\":[\"abp-toolbarbutton\",\"action-button--b9db16a4-6edc-47ec-a1f4-b86292ed211d-vdh-tbbutton\",\"ublock0-button\",\"action-button--firefoxghosterycom-ghostery-button\",\"toggle-button--compatibilityaddonsmozillaorg-acr-dialog\",\"status4evar-legacy-widget\",\"loop-button\",\"pocket-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\",\"ctraddon_addon-bar\",\"ctraddon_extra-bar\",\"web-developer-toolbar\",\"status4evar-status-bar\"],\"currentVersion\":6,\"newElementCount\":92}");

Breaks:
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\",\"widget:compatibility@addons.mozilla.org-acr-dialog\"],\"PersonalToolbar\":[\"__empty\"],\"nav-bar\":[\"unified-back-forward-button\",\"reload-button\",\"stop-button\",\"perspectives-status-button\",\"urlbar-container\",\"dwhelper-toolbaritem\",\"BetterPrivacyButton\",\"secureLoginButton\",\"noscript-tbb\",\"downloads-button\",\"abp-toolbarbutton\",\"home-button\",\"window-controls\",\"bookmarks-menu-button\",\"downbarMini\",\"navigator-throbber\",\"webrtc-status-button\",\"social-share-button\",\"fireftp-button\",\"fvd_single_button\",\"greasemonkey-tbb\",\"loop-button\",\"pocket-button\",\"toggle-button--compatibilityaddonsmozillaorg-acr-dialog\"],\"TabsToolbar\":[\"appmenu-toolbar-button\",\"new-tab-button\",\"alltabs-button\",\"tabs-closebutton\",\"tabbrowser-tabs\",\"treestyletab-tabbar-resizer-box\"],\"toolbar-menubar\":[\"menubar-items\",\"customizableui-special-spring3\",\"linkwidget-top\",\"linkwidget-up\",\"linkwidget-first\",\"linkwidget-prev\",\"linkwidget-next\",\"linkwidget-last\",\"linkwidget-more-menu\",\"customizableui-special-spring4\",\"personal-bookmarks\",\"web-developer-button\",\"useragentswitcher-button\"],\"status4evar-status-bar\":[\"status4evar-status-widget\",\"status4evar-progress-widget\",\"status4evar-download-button\",\"status4evar-legacy-widget\"],\"web-developer-toolbar\":[\"web-developer-disable-toolbar\",\"web-developer-cookies-toolbar\",\"web-developer-css-toolbar\",\"web-developer-forms-toolbar\",\"web-developer-images-toolbar\",\"web-developer-information-toolbar\",\"web-developer-miscellaneous-toolbar\",\"web-developer-outline-toolbar\",\"web-developer-resize-toolbar\",\"web-developer-tools-toolbar\",\"web-developer-view-source-toolbar\",\"web-developer-options-toolbar\",\"customizableui-special-spring2\",\"web-developer-render-mode-statusbar\",\"web-developer-css-statusbar\",\"web-developer-javascript-statusbar\"]},\"seen\":[\"loop-button\",\"pocket-button\",\"abp-toolbarbutton\",\"toggle-button--compatibilityaddonsmozillaorg-acr-dialog\",\"status4evar-legacy-widget\"],\"dirtyAreaCache\":[\"web-developer-toolbar\",\"addon-bar\",\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"status4evar-status-bar\"],\"currentVersion\":6,\"newElementCount\":10}");

Now, it is evident that this setting is somehow related to which button is configured where, noted down in JSON. But I don't know which part is wrong, and what is supposed to set it.

It is also evident that firefox doesn't clean up for 5¢ when removing addons... :/

Does that help debugging it?

**Comment by tadu** [comment] 2016-05-05 13:52
Adding "search-container" after the "urlbar-container" in the "nav-bar" in "placements" in the JSON-hash in browser.uiCustomization.state fixes it.

**Comment by PikachuEXE** [comment] 2016-05-05 13:54
Ha o.0?
Really hard to understand what happened

**Comment by tadu** [comment] 2016-05-05 14:13
It gets more crazy. Adding the "search-container" adds a Search box to my Navigation bar (so far, no surprise). If I remove it again (via the customization UI), and restart the browser, then it breaks again. If I re-add it again via the I, then it works again.

What does sorting tabs have to do with having a search bar???

**Comment by PikachuEXE** [comment] 2016-05-05 14:15
Hmm let me check whether there is any code trying to interact with search box
on Sunday :P

**Comment by tadu** [comment] 2016-05-05 14:16
./content/tabkit.js:      const searchbar = document.getElementById("searchbar");

If there is no searchbar, then...?

**Comment by tadu** [comment] 2016-05-05 15:52
This trivial fix fixes it:

--- ./content/tabkit.js 2016-04-24 18:37:00.000000000 +0200
+++ ./t/content/tabkit.js       2016-05-05 17:44:00.440833289 +0200
@@ -1652,7 +1652,7 @@
       "use strict";
 
       const searchbar = document.getElementById("searchbar");
-      if (!("handleSearchCommand" in searchbar) || typeof searchbar.handleSearchCommand !== "function") {
+      if (!searchbar || !("handleSearchCommand" in searchbar) || typeof searchbar.handleSearchCommand !== "function") {
         tk.debug("searchbar.handleSearchCommand doesn't exists, replacing function failed");
         return;
       }

**Comment by PikachuEXE** [comment] 2016-05-08 03:44
Wow you know how to replace the code :O
I fixed the code for patching to detect `null` but if someone add search bar AFTER browser started TabKit won't work until a new window is created
Well I guess that's acceptable :P

**Comment by PikachuEXE** [comment] 2016-05-08 04:14
[tk2_beta.zip](https://github.com/tabkit/tabkit2/files/253756/tk2_beta.zip)
Try this version
But you need to disable the original one to make it work properly
(This file is signed by creaing another addon and submit without listing it)

**Comment by tadu** [comment] 2016-05-08 10:23
As far as I can see with a short check, it works for me. Thanks!

**Comment by PikachuEXE** [comment] 2016-05-15 04:03
Closing until reported as not fixed :P

**Closed by PikachuEXE** 2016-05-15 04:03 UTC
