### ISSUE TITLE
Unable to drag scrollbar's bar/thumb, will drag window instead.

### ISSUE THREAD

**Issue by arifsaha** [tabkit/tabkit2#87] opened 2015-08-13 19:46 UTC
When the tab bar shown on the right, dragging the bar/thumb of the scrollbar of the tab bar will cause the whole window move / dragged, while the bar/thumb will stay put relatively to the scrollbar and the tab bar is not scrolled. Therefore the scrollbar's bar/thumb is unusable / non functional for the purpose of scrolling.

Experienced in the latest Firefox ESR - version 38*esr. In the main Firefox, the issue occur in much earlier version, 35 or even earlier. The issue does not occur in version 31.

Clicking the empty part of the scrollbar still bringing the bar/thumb toward it and scroll the tab bar, as expected.

**Comment by PikachuEXE** [comment] 2015-08-16 06:35
# My test environment
![env](https://cloud.githubusercontent.com/assets/1018543/9292306/f94fcb20-4422-11e5-989f-0ab980968626.png)
- Firefox ESR 38.0.2 (Portable)
- Windows 7
- Extension 0.12.2.1

# Test Result
Using mouse wheel: **OK**
Dragging scroll bar on tab bar: **OK**
Clicking empty part of scroll bar: **OK**

So I don't understand how to reproduce your problem
Can you provide your OS, Firefox versions, Tab Kit version, and a list of other extensions? (if too many then use screenshot or ignore it)

You can also try using portable Firefox to create a clean environment and installing your existing extensions one by one to find out if the problem is caused by another extension.

**Comment by arifsaha** [comment] 2015-09-06 14:53
The issue came up in Mac OS X 10.8 and 10.9. Firefox 38* ESR (and earlier non-ESR version). Tab Kit always updated (i.e. latest version). Other extensions are NoScript, OmniBar, Prefbar, and FlastGot.
I haven't the chance to try it in clean environment but I experience it in 2 non-related installations of Firefox in Mac OS X (one 10.8 and the other 10.9).

**Comment by PikachuEXE** [comment] 2015-10-02 04:37
I finally got time to fix this issue
Please try this build:
https://bintray.com/tabkit/tabkit2/firefox_extension_package/0.12.3.alpha-2/view

The fix is found at https://bugzilla.mozilla.org/show_bug.cgi?id=1070038
So I just use the same fix from it on scrollbar

This is not a bug in Firefox though since they only expect tab bar to have scroll buttons only.

**Comment by arifsaha** [comment] 2015-10-07 06:24
The 0.12.3.alpha-2 works great! Thank you!
Hopefully this will be merged into the next release.

**Comment by PikachuEXE** [comment] 2015-10-07 06:25
It will, once it's tested by you guys :)
I will test it myself too (using OSX at work)

**Comment by PikachuEXE** [comment] 2015-10-11 02:14
Closing due to release of `0.12.3`

**Closed by PikachuEXE** 2015-10-11 02:14 UTC
Labels: os/osx
