### ISSUE TITLE
Mozilla's Firefox finally enters the 64-bit era on Windows

### ISSUE THREAD

**Issue by amatesi** [tabkit/tabkit2#93] opened 2015-12-23 06:24 UTC
Hi all and thank you for your contribution.

- Is tabkit2 compatible with Mozilla Firefox 64-bit on Windows? What about XUL-dependencies (if any)?

Rel. articles:
http://www.pcworld.com/article/3015715/software/mozillas-firefox-finally-enters-the-64-bit-era-on-windows.html

http://liliputing.com/2015/08/firefox-to-gain-support-for-chrome-add-ons-and-lose-support-for-legacy-xul-plugins.html

Input/clarification(s) appreciated.

Thanks.

Regards,
Andrea.

**Comment by PikachuEXE** [comment] 2015-12-23 06:44
For 64-bit versions, I think it's fine.
Most of the time the problem is from the changes (and not improvements) they make from time to time.

For deprecation of XUL, I cannot be sure at this point.

My wild guess would be:
Even it can be migrated, **some** features must be lost.

If they really remove XUL and the extension stop working, either I will still "maintain" the plugin for old versions of Firefox / switch to forks of Firefox, or I will try to rewrite it for new Firefox with (if I am really willing to do so at that time).

**Comment by PikachuEXE** [comment] 2015-12-23 06:46
To see comment from author some other authors for this news see
https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/comment-page-1/#comments

It's a linked page from one of the articles you posted.

**Comment by PikachuEXE** [comment] 2016-05-01 12:55
Closing since nothing urgent need to be done *yet* :P

**Closed by PikachuEXE** 2016-05-01 12:55 UTC
Labels: kind/question
